### ISSUE TITLE
Viewer not working

### ISSUE THREAD

**Issue by burner1024** [rotators/fallout-animations#2]
All I get is 
![Captura de pantalla de 2022-07-07 10-57-41](https://user-images.githubusercontent.com/1279852/177687555-90341a88-061e-4314-a040-a2138372ec7b.png)

**Comment by ghost2238** [comment]
Made some fixes in https://github.com/rotators/fallout-animations/commit/79378cd5cd2c60061f3aeb27931deb5fa7d81033

Your is issue is likely because a critter that wasn't uploaded was loaded, then this selected critter was saved to localStorage.

All animations should work now. 

If you still get this issue, use https://rotators.fodev.net/ghosthack/scrapheap/anim_viewer/?clear_localstorage=1 - it'll reset the localStorage variables related to critter.

**Comment by burner1024** [comment]
Seems to be working now, thanks.
